# Decision Tree

## 1. Iris 데이터 분류

### 1) scikit 활용한 Iris(붓꽃) Data Set 로드

- 요구되는 패키지
  - pydot2
- 요구되는 프로그램
  - GraphViz: http://www.graphviz.org/
  - MAC에서 설치하는 방법
     - brew install graphviz

In [1]:
from sklearn.datasets import load_iris
from sklearn import tree
from sklearn.externals.six import StringIO

iris = load_iris()
print type(iris)

<class 'sklearn.datasets.base.Bunch'>


In [2]:
iris.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [3]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### 2) DecisionTreeClassifier를 활용한 결정 트리 분류

- classifier (clf) 객체 생성 및 학습
  - DecisionTreeClassifier 객체 활용
  - criterion
    - 'gini': Gini impurity
    - 'entropy': information gain

In [4]:
clf = tree.DecisionTreeClassifier(criterion='entropy')
clf = clf.fit(iris.data, iris.target)

In [5]:
with open("iris.dot", 'w') as f:
    tree.export_graphviz(clf, out_file=f)

- 위 코드까지 수행하면 동일 디렉토리에 iris.dot 파일이 생성됨
- 콘솔에서 다음 명령어로 각종 이미지 파일을 만들 수 있음
 - dot -Tpdf iris.dot > iris.pdf
 - dot -Tpng iris.dot > iris.png

<img src="./iris.png"/>

- classifier (clf) 객체를 활용한 새로운 데이터에 대한 분류 추론
  - predict 함수 활용

In [6]:
iris.data[:1]

array([[ 5.1,  3.5,  1.4,  0.2]])

In [7]:
clf.predict(iris.data[:1])

array([0])

In [8]:
iris.target_names[clf.predict(iris.data[:1])]

array(['setosa'], 
      dtype='|S10')

In [6]:
clf.predict_proba(iris.data[:1])

array([[ 1.,  0.,  0.]])

In [11]:
clf.predict_proba(iris.data[40:110])

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.

## 2. Mushroom 데이터 분류

### 1) Mushroom Data Set 로드 및 scikit을 활용하기 위한 데이터 분리

In [38]:
import urllib2
from scipy import stats
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data'
raw_csv = urllib2.urlopen(path)
col_names = range(23)
df = pd.read_csv(raw_csv, names = col_names)

In [39]:
df

0  1  2  3  4  5  6  7  8  9  ... 13 14 15 16 17 18 19 20 21 22
0     p  x  s  n  t  p  f  c  n  k ...  s  w  w  p  w  o  p  k  s  u
1     e  x  s  y  t  a  f  c  b  k ...  s  w  w  p  w  o  p  n  n  g
2     e  b  s  w  t  l  f  c  b  n ...  s  w  w  p  w  o  p  n  n  m
3     p  x  y  w  t  p  f  c  n  n ...  s  w  w  p  w  o  p  k  s  u
4     e  x  s  g  f  n  f  w  b  k ...  s  w  w  p  w  o  e  n  a  g
5     e  x  y  y  t  a  f  c  b  n ...  s  w  w  p  w  o  p  k  n  g
6     e  b  s  w  t  a  f  c  b  g ...  s  w  w  p  w  o  p  k  n  m
7     e  b  y  w  t  l  f  c  b  n ...  s  w  w  p  w  o  p  n  s  m
8     p  x  y  w  t  p  f  c  n  p ...  s  w  w  p  w  o  p  k  v  g
9     e  b  s  y  t  a  f  c  b  g ...  s  w  w  p  w  o  p  k  s  m
10    e  x  y  y  t  l  f  c  b  g ...  s  w  w  p  w  o  p  n  n  g
11    e  x  y  y  t  a  f  c  b  n ...  s  w  w  p  w  o  p  k  s  m
12    e  b  s  y  t  a  f  c  b  w ...  s  w  w  p  w  o  p  n  s  g
13    p  x  y  w  t  p  f  c  n  k ...  s  w  w  p  w  o  p  n  v  u
14    e  x  f  n  f  n  f  w  b  n ...  f  w  w  p  w  o  e  k  a  g
15    e  s  f  g  f  n  f  c  n  k ...  s  w  w  p  w  o  p  n  y  u
16    e  f  f  w  f  n  f  w  b  k ...  s  w  w  p  w  o  e  n  a  g
17    p  x  s  n  t  p  f  c  n  n ...  s  w  w  p  w  o  p  k  s  g
18    p  x  y  w  t  p  f  c  n  n ...  s  w  w  p  w  o  p  n  s  u
19    p  x  s  n  t  p  f  c  n  k ...  s  w  w  p  w  o  p  n  s  u
20    e  b  s  y  t  a  f  c  b  k ...  s  w  w  p  w  o  p  n  s  m
21    p  x  y  n  t  p  f  c  n  n ...  s  w  w  p  w  o  p  n  v  g
22    e  b  y  y  t  l  f  c  b  k ...  s  w  w  p  w  o  p  n  s  m
23    e  b  y  w  t  a  f  c  b  w ...  s  w  w  p  w  o  p  n  n  m
24    e  b  s  w  t  l  f  c  b  g ...  s  w  w  p  w  o  p  k  s  m
25    p  f  s  w  t  p  f  c  n  n ...  s  w  w  p  w  o  p  n  v  g
26    e  x  y  y  t  a  f  c  b  n ...  s  w  w  p  w  o  p  n  n  m
27    e  x  y  w  t  l  f  c  b  w ...  s  w  w  p  w  o  p  n  n  m
28    e  f  f  n  f  n  f  c  n  k ...  s  w  w  p  w  o  p  k  y  u
29    e  x  s  y  t  a  f  w  n  n ...  s  w  w  p  w  o  p  n  v  d
...  .. .. .. .. .. .. .. .. .. .. ... .. .. .. .. .. .. .. .. .. ..
8094  e  b  s  g  f  n  f  w  b  g ...  s  w  w  p  w  t  p  w  n  g
8095  p  x  y  c  f  m  f  c  b  y ...  y  c  c  p  w  n  n  w  c  d
8096  e  k  f  w  f  n  f  w  b  w ...  s  w  w  p  w  t  p  w  n  g
8097  p  k  y  n  f  s  f  c  n  b ...  k  p  p  p  w  o  e  w  v  l
8098  p  k  s  e  f  y  f  c  n  b ...  k  w  p  p  w  o  e  w  v  d
8099  e  k  f  w  f  n  f  w  b  w ...  k  w  w  p  w  t  p  w  s  g
8100  e  f  s  n  f  n  a  c  b  o ...  s  o  o  p  n  o  p  b  v  l
8101  p  k  s  e  f  s  f  c  n  b ...  s  p  w  p  w  o  e  w  v  p
8102  e  x  s  n  f  n  a  c  b  y ...  s  o  o  p  n  o  p  n  c  l
8103  e  k  s  n  f  n  a  c  b  y ...  s  o  o  p  n  o  p  o  c  l
8104  e  k  s  n  f  n  a  c  b  y ...  s  o  o  p  o  o  p  n  v  l
8105  e  k  s  n  f  n  a  c  b  y ...  s  o  o  p  n  o  p  y  v  l
8106  e  k  s  n  f  n  a  c  b  o ...  s  o  o  p  o  o  p  n  v  l
8107  e  x  s  n  f  n  a  c  b  y ...  s  o  o  p  o  o  p  n  c  l
8108  p  k  y  e  f  y  f  c  n  b ...  s  p  w  p  w  o  e  w  v  l
8109  e  b  s  w  f  n  f  w  b  w ...  s  w  w  p  w  t  p  w  n  g
8110  e  x  s  n  f  n  a  c  b  o ...  s  o  o  p  o  o  p  n  v  l
8111  e  k  s  w  f  n  f  w  b  p ...  s  w  w  p  w  t  p  w  n  g
8112  e  k  s  n  f  n  a  c  b  o ...  s  o  o  p  n  o  p  b  v  l
8113  p  k  y  e  f  y  f  c  n  b ...  k  p  p  p  w  o  e  w  v  d
8114  p  f  y  c  f  m  a  c  b  y ...  y  c  c  p  w  n  n  w  c  d
8115  e  x  s  n  f  n  a  c  b  y ...  s  o  o  p  o  o  p  o  v  l
8116  p  k  y  n  f  s  f  c  n  b ...  k  p  w  p  w  o  e  w  v  l
8117  p  k  s  e  f  y  f  c  n  b ...  s  p  w  p  w  o  e  w  v  d
8118  p  k  y  n  f  f  f  c  n  b ...  s  p  w  p  w  o  e  w  v  d
8119  e  k  s  n  f  n  a  c  b  y ...  s  o  o  p  o  o  p  b  c  l
812

- categorical 데이터를 ordered 데이터로 변경

In [40]:
df[0] = df[0].map({'p': 1, 'e': 0})
df

0  1  2  3  4  5  6  7  8  9  ... 13 14 15 16 17 18 19 20 21 22
0      1  x  s  n  t  p  f  c  n  k ...  s  w  w  p  w  o  p  k  s  u
1      0  x  s  y  t  a  f  c  b  k ...  s  w  w  p  w  o  p  n  n  g
2      0  b  s  w  t  l  f  c  b  n ...  s  w  w  p  w  o  p  n  n  m
3      1  x  y  w  t  p  f  c  n  n ...  s  w  w  p  w  o  p  k  s  u
4      0  x  s  g  f  n  f  w  b  k ...  s  w  w  p  w  o  e  n  a  g
5      0  x  y  y  t  a  f  c  b  n ...  s  w  w  p  w  o  p  k  n  g
6      0  b  s  w  t  a  f  c  b  g ...  s  w  w  p  w  o  p  k  n  m
7      0  b  y  w  t  l  f  c  b  n ...  s  w  w  p  w  o  p  n  s  m
8      1  x  y  w  t  p  f  c  n  p ...  s  w  w  p  w  o  p  k  v  g
9      0  b  s  y  t  a  f  c  b  g ...  s  w  w  p  w  o  p  k  s  m
10     0  x  y  y  t  l  f  c  b  g ...  s  w  w  p  w  o  p  n  n  g
11     0  x  y  y  t  a  f  c  b  n ...  s  w  w  p  w  o  p  k  s  m
12     0  b  s  y  t  a  f  c  b  w ...  s  w  w  p  w  o  p  n  s  g
13     1  x  y  w  t  p  f  c  n  k ...  s  w  w  p  w  o  p  n  v  u
14     0  x  f  n  f  n  f  w  b  n ...  f  w  w  p  w  o  e  k  a  g
15     0  s  f  g  f  n  f  c  n  k ...  s  w  w  p  w  o  p  n  y  u
16     0  f  f  w  f  n  f  w  b  k ...  s  w  w  p  w  o  e  n  a  g
17     1  x  s  n  t  p  f  c  n  n ...  s  w  w  p  w  o  p  k  s  g
18     1  x  y  w  t  p  f  c  n  n ...  s  w  w  p  w  o  p  n  s  u
19     1  x  s  n  t  p  f  c  n  k ...  s  w  w  p  w  o  p  n  s  u
20     0  b  s  y  t  a  f  c  b  k ...  s  w  w  p  w  o  p  n  s  m
21     1  x  y  n  t  p  f  c  n  n ...  s  w  w  p  w  o  p  n  v  g
22     0  b  y  y  t  l  f  c  b  k ...  s  w  w  p  w  o  p  n  s  m
23     0  b  y  w  t  a  f  c  b  w ...  s  w  w  p  w  o  p  n  n  m
24     0  b  s  w  t  l  f  c  b  g ...  s  w  w  p  w  o  p  k  s  m
25     1  f  s  w  t  p  f  c  n  n ...  s  w  w  p  w  o  p  n  v  g
26     0  x  y  y  t  a  f  c  b  n ...  s  w  w  p  w  o  p  n  n  m
27     0  x  y  w  t  l  f  c  b  w ...  s  w  w  p  w  o  p  n  n  m
28     0  f  f  n  f  n  f  c  n  k ...  s  w  w  p  w  o  p  k  y  u
29     0  x  s  y  t  a  f  w  n  n ...  s  w  w  p  w  o  p  n  v  d
...   .. .. .. .. .. .. .. .. .. .. ... .. .. .. .. .. .. .. .. .. ..
8094   0  b  s  g  f  n  f  w  b  g ...  s  w  w  p  w  t  p  w  n  g
8095   1  x  y  c  f  m  f  c  b  y ...  y  c  c  p  w  n  n  w  c  d
8096   0  k  f  w  f  n  f  w  b  w ...  s  w  w  p  w  t  p  w  n  g
8097   1  k  y  n  f  s  f  c  n  b ...  k  p  p  p  w  o  e  w  v  l
8098   1  k  s  e  f  y  f  c  n  b ...  k  w  p  p  w  o  e  w  v  d
8099   0  k  f  w  f  n  f  w  b  w ...  k  w  w  p  w  t  p  w  s  g
8100   0  f  s  n  f  n  a  c  b  o ...  s  o  o  p  n  o  p  b  v  l
8101   1  k  s  e  f  s  f  c  n  b ...  s  p  w  p  w  o  e  w  v  p
8102   0  x  s  n  f  n  a  c  b  y ...  s  o  o  p  n  o  p  n  c  l
8103   0  k  s  n  f  n  a  c  b  y ...  s  o  o  p  n  o  p  o  c  l
8104   0  k  s  n  f  n  a  c  b  y ...  s  o  o  p  o  o  p  n  v  l
8105   0  k  s  n  f  n  a  c  b  y ...  s  o  o  p  n  o  p  y  v  l
8106   0  k  s  n  f  n  a  c  b  o ...  s  o  o  p  o  o  p  n  v  l
8107   0  x  s  n  f  n  a  c  b  y ...  s  o  o  p  o  o  p  n  c  l
8108   1  k  y  e  f  y  f  c  n  b ...  s  p  w  p  w  o  e  w  v  l
8109   0  b  s  w  f  n  f  w  b  w ...  s  w  w  p  w  t  p  w  n  g
8110   0  x  s  n  f  n  a  c  b  o ...  s  o  o  p  o  o  p  n  v  l
8111   0  k  s  w  f  n  f  w  b  p ...  s  w  w  p  w  t  p  w  n  g
8112   0  k  s  n  f  n  a  c  b  o ...  s  o  o  p  n  o  p  b  v  l
8113   1  k  y  e  f  y  f  c  n  b ...  k  p  p  p  w  o  e  w  v  d
8114   1  f  y  c  f  m  a  c  b  y ...  y  c  c  p  w  n  n  w  c  d
8115   0  x  s  n  f  n  a  c  b  y ...  s  o  o  p  o  o  p  o  v  l
8116   1  k  y  n  f  s  f  c  n  b ...  k  p  w  p  w  o  e  w  v  l
8117   1  k  s  e  f  y  f  c  n  b ...  s  p  w  p  w  o  e  w  v  d
8118   1  k  y  n  f  f  f  c  n  b ...  s  p  w  p  w  o  e  w  v  d
8119   0  k  s  

In [13]:
map_dic = {}
num_columns = df.shape[1]
for i in range(num_columns):
    unique_array = df[i].unique()
    map_dic_sub = {}
    for j in range(len(unique_array)):
        map_dic_sub[unique_array[j]] = j
    df[i] = df[i].map(map_dic_sub)
df

0   1   2   3   4   5   6   7   8   9  ...  13  14  15  16  17  18  19  \
0      0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
1      1   0   0   1   0   1   0   0   1   0 ...   0   0   0   0   0   0   0   
2      1   1   0   2   0   2   0   0   1   1 ...   0   0   0   0   0   0   0   
3      0   0   1   2   0   0   0   0   0   1 ...   0   0   0   0   0   0   0   
4      1   0   0   3   1   3   0   1   1   0 ...   0   0   0   0   0   0   1   
5      1   0   1   1   0   1   0   0   1   1 ...   0   0   0   0   0   0   0   
6      1   1   0   2   0   1   0   0   1   2 ...   0   0   0   0   0   0   0   
7      1   1   1   2   0   2   0   0   1   1 ...   0   0   0   0   0   0   0   
8      0   0   1   2   0   0   0   0   0   3 ...   0   0   0   0   0   0   0   
9      1   1   0   1   0   1   0   0   1   2 ...   0   0   0   0   0   0   0   
10     1   0   1   1   0   2   0   0   1   2 ...   0   0   0   0   0   0   0   
11     1   0   1   1   0   1   0   0   1   1 ...   0   0   0   0   0   0   0   
12     1   1   0   1   0   1   0   0   1   4 ...   0   0   0   0   0   0   0   
13     0   0   1   2   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
14     1   0   2   0   1   3   0   1   1   1 ...   1   0   0   0   0   0   1   
15     1   2   2   3   1   3   0   0   0   0 ...   0   0   0   0   0   0   0   
16     1   3   2   2   1   3   0   1   1   0 ...   0   0   0   0   0   0   1   
17     0   0   0   0   0   0   0   0   0   1 ...   0   0   0   0   0   0   0   
18     0   0   1   2   0   0   0   0   0   1 ...   0   0   0   0   0   0   0   
19     0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
20     1   1   0   1   0   1   0   0   1   0 ...   0   0   0   0   0   0   0   
21     0   0   1   0   0   0   0   0   0   1 ...   0   0   0   0   0   0   0   
22     1   1   1   1   0   2   0   0   1   0 ...   0   0   0   0   0   0   0   
23     1   1   1   2   0   1   0   0   1   4 ...   0   0   0   0   0   0   0   
24     1   1   0   2   0   2   0   0   1   2 ...   0   0   0   0   0   0   0   
25     0   3   0   2   0   0   0   0   0   1 ...   0   0   0   0   0   0   0   
26     1   0   1   1   0   1   0   0   1   1 ...   0   0   0   0   0   0   0   
27     1   0   1   2   0   2   0   0   1   4 ...   0   0   0   0   0   0   0   
28     1   3   2   0   1   3   0   0   0   0 ...   0   0   0   0   0   0   0   
29     1   0   0   1   0   1   0   1   0   1 ...   0   0   0   0   0   0   0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  .. ...  ..  ..  ..  ..  ..  ..  ..   
8094   1   1   0   3   1   3   0   1   1   2 ...   0   0   0   0   0   1   0   
8095   0   0   1   8   1   8   0   0   1  10 ...   2   7   8   0   0   2   4   
8096   1   4   2   2   1   3   0   1   1   4 ...   0   0   0   0   0   1   0   
8097   0   4   1   0   1   7   0   0   0   8 ...   3   2   1   0   0   0   1   
8098   0   4   0   4   1   6   0   0   0   8 ...   3   0   1   0   0   0   1   
8099   1   4   2   2   1   3   0   1   1   4 ...   3   0   0   0   0   1   0   
8100   1   3   0   0   1   3   1   0   1  11 ...   0   6   7   0   1   0   0   
8101   0   4   0   4   1   7   0   0   0   8 ...   0   2   0   0   0   0   1   
8102   1   0   0   0   1   3   1   0   1  10 ...   0   6   7   0   1   0   0   
8103   1   4   0   0   1   3   1   0   1  10 ...   0   6   7   0   1   0   0   
8104   1   4   0   0   1   3   1   0   1  10 ...   0   6   7   0   2   0   0   
8105   1   4   0   0   1   3   1   0   1  10 ...   0   6   7   0   1   0   0   
8106   1   4   0   0   1   3   1   0   1  11 ...   0   6   7   0   2   0   0   
8107   1   0   0   0   1   3   1   0   1  10 ...   0   6   7   0   2   0   0   
8108   0   4   1   4   1   6   0   0   0   8 ...   0   2   0   0   0   0   1   
8109   1   1   0   2   1   3   0   1   1   4 ...   0   0   0   0   0   1   0   
8110   1   0   0   0   1   3   1   0   1  11 ...   0   6   7   0   2   0   0   
8111   1   4   0   2   1   3   0   1   1   3 ...   0   0   0   0   0   1   0   
8112  

In [42]:
attributes = df.iloc[:, 1:23]
attributes

1   2   3   4   5   6   7   8   9   10 ...  13  14  15  16  17  18  19  \
0      0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
1      0   0   1   0   1   0   0   1   0   0 ...   0   0   0   0   0   0   0   
2      1   0   2   0   2   0   0   1   1   0 ...   0   0   0   0   0   0   0   
3      0   1   2   0   0   0   0   0   1   0 ...   0   0   0   0   0   0   0   
4      0   0   3   1   3   0   1   1   0   1 ...   0   0   0   0   0   0   1   
5      0   1   1   0   1   0   0   1   1   0 ...   0   0   0   0   0   0   0   
6      1   0   2   0   1   0   0   1   2   0 ...   0   0   0   0   0   0   0   
7      1   1   2   0   2   0   0   1   1   0 ...   0   0   0   0   0   0   0   
8      0   1   2   0   0   0   0   0   3   0 ...   0   0   0   0   0   0   0   
9      1   0   1   0   1   0   0   1   2   0 ...   0   0   0   0   0   0   0   
10     0   1   1   0   2   0   0   1   2   0 ...   0   0   0   0   0   0   0   
11     0   1   1   0   1   0   0   1   1   0 ...   0   0   0   0   0   0   0   
12     1   0   1   0   1   0   0   1   4   0 ...   0   0   0   0   0   0   0   
13     0   1   2   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
14     0   2   0   1   3   0   1   1   1   1 ...   1   0   0   0   0   0   1   
15     2   2   3   1   3   0   0   0   0   0 ...   0   0   0   0   0   0   0   
16     3   2   2   1   3   0   1   1   0   1 ...   0   0   0   0   0   0   1   
17     0   0   0   0   0   0   0   0   1   0 ...   0   0   0   0   0   0   0   
18     0   1   2   0   0   0   0   0   1   0 ...   0   0   0   0   0   0   0   
19     0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
20     1   0   1   0   1   0   0   1   0   0 ...   0   0   0   0   0   0   0   
21     0   1   0   0   0   0   0   0   1   0 ...   0   0   0   0   0   0   0   
22     1   1   1   0   2   0   0   1   0   0 ...   0   0   0   0   0   0   0   
23     1   1   2   0   1   0   0   1   4   0 ...   0   0   0   0   0   0   0   
24     1   0   2   0   2   0   0   1   2   0 ...   0   0   0   0   0   0   0   
25     3   0   2   0   0   0   0   0   1   0 ...   0   0   0   0   0   0   0   
26     0   1   1   0   1   0   0   1   1   0 ...   0   0   0   0   0   0   0   
27     0   1   2   0   2   0   0   1   4   0 ...   0   0   0   0   0   0   0   
28     3   2   0   1   3   0   0   0   0   0 ...   0   0   0   0   0   0   0   
29     0   0   1   0   1   0   1   0   1   1 ...   0   0   0   0   0   0   0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  .. ...  ..  ..  ..  ..  ..  ..  ..   
8094   1   0   3   1   3   0   1   1   2   0 ...   0   0   0   0   0   1   0   
8095   0   1   8   1   8   0   0   1  10   0 ...   2   7   8   0   0   2   4   
8096   4   2   2   1   3   0   1   1   4   0 ...   0   0   0   0   0   1   0   
8097   4   1   0   1   7   0   0   0   8   1 ...   3   2   1   0   0   0   1   
8098   4   0   4   1   6   0   0   0   8   1 ...   3   0   1   0   0   0   1   
8099   4   2   2   1   3   0   1   1   4   0 ...   3   0   0   0   0   1   0   
8100   3   0   0   1   3   1   0   1  11   0 ...   0   6   7   0   1   0   0   
8101   4   0   4   1   7   0   0   0   8   1 ...   0   2   0   0   0   0   1   
8102   0   0   0   1   3   1   0   1  10   0 ...   0   6   7   0   1   0   0   
8103   4   0   0   1   3   1   0   1  10   0 ...   0   6   7   0   1   0   0   
8104   4   0   0   1   3   1   0   1  10   0 ...   0   6   7   0   2   0   0   
8105   4   0   0   1   3   1   0   1  10   0 ...   0   6   7   0   1   0   0   
8106   4   0   0   1   3   1   0   1  11   0 ...   0   6   7   0   2   0   0   
8107   0   0   0   1   3   1   0   1  10   0 ...   0   6   7   0   2   0   0   
8108   4   1   4   1   6   0   0   0   8   1 ...   0   2   0   0   0   0   1   
8109   1   0   2   1   3   0   1   1   4   0 ...   0   0   0   0   0   1   0   
8110   0   0   0   1   3   1   0   1  11   0 ...   0   6   7   0   2   0   0   
8111   4   0   2   1   3   0   1   1   3   0 ...   0   0   0   0   0   1   0   
8112  

In [43]:
mushroom_data = attributes.values
mushroom_data

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 1, 1],
       [1, 0, 2, ..., 1, 1, 2],
       ..., 
       [3, 0, 0, ..., 8, 5, 6],
       [4, 1, 0, ..., 4, 3, 6],
       [0, 0, 0, ..., 6, 5, 6]])

In [44]:
target_series = df.iloc[:, 0]
target_series

0       0
1       1
2       1
3       0
4       1
5       1
6       1
7       1
8       0
9       1
10      1
11      1
12      1
13      0
14      1
15      1
16      1
17      0
18      0
19      0
20      1
21      0
22      1
23      1
24      1
25      0
26      1
27      1
28      1
29      1
       ..
8094    1
8095    0
8096    1
8097    0
8098    0
8099    1
8100    1
8101    0
8102    1
8103    1
8104    1
8105    1
8106    1
8107    1
8108    0
8109    1
8110    1
8111    1
8112    1
8113    0
8114    0
8115    1
8116    0
8117    0
8118    0
8119    1
8120    1
8121    1
8122    0
8123    1
Name: 0, dtype: int64

In [45]:
mushroom_target = target_series.values
mushroom_target

array([0, 1, 1, ..., 1, 0, 1])

### 2) DecisionTreeClassifier를 활용한 결정 트리 분류

In [46]:
clf2 = tree.DecisionTreeClassifier(criterion='entropy')
clf2 = clf.fit(mushroom_data, mushroom_target)

In [47]:
with open("mushroom.dot", 'w') as f2:
    tree.export_graphviz(clf2, out_file=f2)

<img src="./mushroom.png"/>

- classifier (clf2) 객체를 활용한 새로운 데이터에 대한 분류 추론

In [24]:
mushroom_data[-1]

array([ 0,  0,  0,  1,  3,  1,  0,  1, 10,  0,  4,  0,  0,  6,  7,  0,  2,
        0,  0,  6,  5,  6])

In [25]:
clf2.predict(mushroom_data[-1])

/Users/yhhan/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [26]:
clf2.predict(mushroom_data[-2])

/Users/yhhan/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([0])

## 3. Spark을 활용한 Mushroom 데이터 분류

In [23]:
import urllib2
from scipy import stats
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data'
raw_csv = urllib2.urlopen(path)
col_names = range(23)
df = pd.read_csv(raw_csv, names = col_names)
map_dic = {}
num_columns = df.shape[1]
for i in range(num_columns):
    unique_array = df[i].unique()
    map_dic_sub = {}
    for j in range(len(unique_array)):
        map_dic_sub[unique_array[j]] = j
    df[i] = df[i].map(map_dic_sub)

In [24]:
import findspark     
 
findspark.init()  
from pyspark import SparkContext, SparkFiles, SQLContext

if not 'sc' in locals():  
    sc = SparkContext()  

sqlCtx = SQLContext(sc)
sdf = sqlCtx.createDataFrame(df)
sdf.show()
#sdf.printSchema()
print "Raw data size is %s" % sdf.count()

+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
|  0|  1|  2|  3|  4|  5|  6|  7|  8|  9| 10| 11| 12| 13| 14| 15| 16| 17| 18| 19| 20| 21| 22|
+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|
|  1|  0|  0|  1|  0|  1|  0|  0|  1|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  1|  1|  1|
|  1|  1|  0|  2|  0|  2|  0|  0|  1|  1|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  1|  1|  2|
|  0|  0|  1|  2|  0|  0|  0|  0|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|
|  1|  0|  0|  3|  1|  3|  0|  1|  1|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  1|  1|  2|  1|
|  1|  0|  1|  1|  0|  1|  0|  0|  1|  1|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  1|  1|
|  1|  1|  0|  2|  0|  1|  0|  0|  1|  2|  0|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  1|  2|
|  1|  1|  1|  2|  0|  2|  0|  0|  1|  1|  0|  1|  0|  0|  0

In [25]:
from pyspark.mllib.tree import DecisionTree, LabeledPoint

result = sdf.rdd.map(lambda row: LabeledPoint(row[0], row[1:23]))
(trainingData, testData) = result.randomSplit([0.7, 0.3])
model = DecisionTree.trainClassifier(trainingData, numClasses=2, categoricalFeaturesInfo={},
                                          impurity='gini', maxDepth=4, maxBins=100)
print testData.count()

2447


In [26]:
predictions = model.predict(testData.map(lambda x: x.features))
labelsAndPredictions = testData.map(lambda x: x.label).zip(predictions)

#print labelsAndPredictions.take(100)

errorCount = labelsAndPredictions.filter(lambda (v, p): v != p).count()
print "errorCount = %s" % errorCount
testErr = errorCount / float(testData.count())
print 'Test Error = %s' % testErr
print 'Learned classification tree model:'
print model.toDebugString()

errorCount = 16
Test Error = 0.0065386187168
Learned classification tree model:
DecisionTreeModel classifier of depth 4 with 11 nodes
  If (feature 4 <= 3.0)
   If (feature 4 <= 0.0)
    Predict: 0.0
   Else (feature 4 > 0.0)
    If (feature 19 <= 4.0)
     If (feature 13 <= 6.0)
      Predict: 1.0
     Else (feature 13 > 6.0)
      Predict: 0.0
    Else (feature 19 > 4.0)
     If (feature 2 <= 0.0)
      Predict: 1.0
     Else (feature 2 > 0.0)
      Predict: 0.0
  Else (feature 4 > 3.0)
   Predict: 0.0

