# Single Layer Neural Network

## 1. Basic Usage
- Note: https://www.tensorflow.org/versions/r0.11/get_started/basic_usage.html
- **TensorFlow** is a programming system in which you represent computations as graphs. 
- Nodes in the graph are called **operations**. 
  - An operation takes zero or more Tensors, performs some computation, and produces zero or more Tensors. 
- A **Tensor** is a typed multi-dimensional array. 

In [1]:
import tensorflow as tf
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print "matrix1 -", matrix1
print "matrix2 -", matrix2
matrix3 = tf.matmul(matrix1, matrix2)
print "matrix3 -", matrix3
matrix4 = tf.matmul(matrix2, matrix1)
print "matrix4 -", matrix4

matrix5 = tf.constant([[1., 1.], [2., 2.]])
print "matrix5 -", matrix5
matrix6 = tf.constant([10., 10.])
print "matrix6 -", matrix6
matrix7 = matrix5 + matrix6
print "matrix7 -", matrix7

print 

sess = tf.Session()
matrix3_result = sess.run(matrix3)
print matrix3_result

matrix4_result = sess.run(matrix4)
print matrix4_result

matrix7_result = sess.run(matrix7)
print matrix7_result

matrix1 - Tensor("Const:0", shape=(1, 2), dtype=float32)
matrix2 - Tensor("Const_1:0", shape=(2, 1), dtype=float32)
matrix3 - Tensor("MatMul:0", shape=(1, 1), dtype=float32)
matrix4 - Tensor("MatMul_1:0", shape=(2, 2), dtype=float32)
matrix5 - Tensor("Const_2:0", shape=(2, 2), dtype=float32)
matrix6 - Tensor("Const_3:0", shape=(2,), dtype=float32)
matrix7 - Tensor("add:0", shape=(2, 2), dtype=float32)

[[ 12.]]
[[ 6.  6.]
 [ 6.  6.]]
[[ 11.  11.]
 [ 12.  12.]]


## 2. MNIST handwritten digits image set
- Note1: http://yann.lecun.com/exdb/mnist/
- Note2: https://www.tensorflow.org/versions/r0.11/tutorials/mnist/beginners/index.html

In [2]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [3]:
print type(mnist.train.images), mnist.train.images.shape
print type(mnist.train.labels), mnist.train.labels.shape

<type 'numpy.ndarray'> (55000, 784)
<type 'numpy.ndarray'> (55000, 10)


In [4]:
mnist.train.next_batch(5)

(array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32),
 array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]))

## 3. Neural Network Model

In [5]:
import tensorflow as tf
x = tf.placeholder(tf.float32, [None, 784])

In [6]:
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

In [7]:
y = tf.nn.softmax(tf.matmul(x, W) + b)

In [8]:
y_ = tf.placeholder(tf.float32, [None, 10])

In [9]:
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))

In [10]:
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

## 4. Training

In [11]:
init = tf.initialize_all_variables()

In [12]:
sess = tf.Session()
sess.run(init)

In [13]:
for i in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})

## 5. Evaluation

In [14]:
print y.get_shape()
print y_.get_shape()

(?, 10)
(?, 10)


In [15]:
correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))

In [16]:
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [17]:
print(sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels}))

0.9129


## 6. All in one

In [18]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
x = tf.placeholder(tf.float32, [None, 784])

W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))
y = tf.nn.softmax(tf.matmul(x, W) + b)

y_ = tf.placeholder(tf.float32, [None, 10])
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

init = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(init)
    for i in range(1000):
        batch_xs, batch_ys = mnist.train.next_batch(100)
        sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})
    correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    print(sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
0.9184
